/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gpagency.solitaire;

import java.io.File;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 *
 * @author Jules
 */
public class VueFichier extends javax.swing.JFrame {

    /**
     * Creates new form VueFichier
     */
    private Paquet paquet;
    private boolean used = false;
    private Operations op;
    
    public VueFichier(Paquet p) {
        paquet=new Paquet(p.getJeu());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lire = new javax.swing.JTextField();
        Ecrire = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Indic = new javax.swing.JTextArea();
        Coder = new javax.swing.JButton();
        Decoder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        Lire.setText("texte.txt");
        getContentPane().add(Lire);

        Ecrire.setText("code.txt");
        getContentPane().add(Ecrire);

        Indic.setEditable(false);
        Indic.setColumns(20);
        Indic.setRows(5);
        Indic.setText("Première case : \nNom du fichier à lire\n\nDeuxième case :\nNom du fichier à écrire");
        jScrollPane1.setViewportView(Indic);

        getContentPane().add(jScrollPane1);

        Coder.setText("Coder");
        Coder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoderActionPerformed(evt);
            }
        });
        getContentPane().add(Coder);

        Decoder.setText("Décoder");
        Decoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecoderActionPerformed(evt);
            }
        });
        getContentPane().add(Decoder);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DecoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecoderActionPerformed
        String content = "vide";
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        System.out.println("Current relative path is: " + s);
        try{
            content = new String(Files.readAllBytes(Paths.get(Lire.getText())), StandardCharsets.UTF_8);
        }catch(Exception e){
            Indic.setText("Fichier à lire absent");
        }
        
        Operations o_code=new Operations(content, this.paquet);
        o_code.decode();
        String text_code=o_code.getMessage_trans();
        
        File transf = new File(Ecrire.getText());
        try{
            transf.createNewFile(); 
        }catch(Exception e){
            Indic.setText("Problème lors de la création du fichier");
        }
        
        try (PrintWriter out = new PrintWriter(Ecrire.getText())) {
            out.println(text_code);
        }catch(Exception e){
            Indic.setText("Problème lors de l'écriture");
        }
    }//GEN-LAST:event_DecoderActionPerformed

    private void CoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoderActionPerformed
        // TODO add your handling code here:
        String content = "vide";
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        System.out.println("Current relative path is: " + s);
        try{
            content = new String(Files.readAllBytes(Paths.get(Lire.getText())), StandardCharsets.UTF_8);
        }catch(Exception e){
            Indic.setText("Fichier à lire absent");
        }
        
        Operations o_code=new Operations(content, this.paquet);
        o_code.code();
        String text_code=o_code.getMessage_trans();
        
        File transf = new File(Ecrire.getText());
        try{
            transf.createNewFile(); 
        }catch(Exception e){
            Indic.setText("Problème lors de la création du fichier");
        }
        
        try (PrintWriter out = new PrintWriter(Ecrire.getText())) {
            out.println(text_code);
        }catch(Exception e){
            Indic.setText("Problème lors de l'écriture");
        }

    }//GEN-LAST:event_CoderActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Coder;
    private javax.swing.JButton Decoder;
    private javax.swing.JTextField Ecrire;
    private javax.swing.JTextArea Indic;
    private javax.swing.JTextField Lire;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
