/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gpagency.solitaire;

/**
 *
 * @author Jules
 */
public class VueFichier extends javax.swing.JFrame {

    /**
     * Creates new form VueFichier
     */
    private Paquet p;
    private boolean used = false;
    private Operations op;
    
    public VueFichier(Paquet p) {
        p=new Paquet(p.getJeu());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lire = new javax.swing.JTextField();
        Ecrire = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Coder = new javax.swing.JButton();
        Decoder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        Lire.setText("text.txt");
        getContentPane().add(Lire);

        Ecrire.setText("text.txt");
        getContentPane().add(Ecrire);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Première case : \nNom du fichier à lire\n\nDeuxième case :\nNom du fichier à écrire");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);

        Coder.setText("Coder");
        getContentPane().add(Coder);

        Decoder.setText("Décoder");
        Decoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecoderActionPerformed(evt);
            }
        });
        getContentPane().add(Decoder);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DecoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecoderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DecoderActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Coder;
    private javax.swing.JButton Decoder;
    private javax.swing.JTextField Ecrire;
    private javax.swing.JTextField Lire;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
